### PR TITLE
[TASK] Align with new TYPO3 documentation standards

### PR DESCRIPTION
**Pull request by alexander-nitsche**
Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/182

### CODE REVIEW

**Comment by alexander-nitsche** [comment]
What is missing: Remove the documentation URL `https://docs.typo3.org/p/friendsoftypo3/frontend-editing/main/en-us/` from the "External manual" field of the TER extension page configuration at https://extensions.typo3.org as the documentation at docs.typo3.org is detected automatically and a specific URL is error-prone.

**Comment by alexander-nitsche** [comment]
How it looks like:
Screen Shot 2022-04-03 at 16 01 19

**Review by mabolek — APPROVED** [review]

**Comment by mabolek** [comment]
Thank you, @alexander-nitsche. This is a fabulous contribution!

**Comment by ohader** [comment]
Removed manual URL from TER settings - sorry @mabolek, I had to hijack that extension, but transferred it back to you folks

**Comment by mabolek** [comment]
@ohader Thank you! I forgot to make that update, so I'm glad you did it — even if it inclided a short-term hijack. 😉

**Pull request merged**
