### PR TITLE
[BUGFIX] Pages showing after editing in frontend

### LINKED ISSUE #402: Pages not showing content after editing in frontend
We are having an issue that popped up after the 1.9.0 release in which we sometimes get a PHP exception thrown on page loading of pages that were opened in frontend editing, at the following line:

https://github.com/FriendsOfTYPO3/frontend_editing/blob/335c06f0946f0706ae8acb040fdf92b0991e6c7b/Classes/Hook/FrontendEditingInitializationHook.php#L172

When the error occurs the $parentObject->content is not set which causes an exception. Weirdly, even clearing cache etc will not fix the problem, from that point on, the page is only viewable when logged in to the backend (i.e. while frontend editing), and completely broken for site visitors, as every call causes the exception. The fix is to deactivate the frontend editing extension, then clear cache and reload the page in question, which works every time.

Rolling back to 1.8.3 fixes this issue entirely it seems. I am sorry, but i cant offer any further input as it does not seem as if the Line referenced above is the root cause.

### LINKED ISSUE #403: Internal links in RTE use incorrect link format (t3://page?uid=215)
Internal links in RTE use link format t3://page?uid=215 even if you are not logged in (this has previously only appeared when logged in).
Screenshot_5

### PR DESCRIPTION
**Pull request by mabolek**
Fixes #402

[BUGFIX] Links use correct link format

Fixes #403

### CODE REVIEW

**Comment by mabolek** [comment]
@kevinandrewsde I'm thinking you're runing this in TYPO3 9.5. Correct? The hook is only there for compatibility and should only be executed in TYPO3 8.7. It shouldn't affect you. However, the changes to the TypoScript template should.

**Comment by kevinandrewsde** [comment]
@mabolek Yes, i am running 9.5 LTS. Ok. But the change to setup.ts does not contain [globalVar = TSFE : beUserLogin > 0], which is what fixes #402 for me.

**Comment by mabolek** [comment]
@kevinandrewsde Yes and no. ;-) It contains the Symfony Expression Language equivalent, `[backend.user.isLoggedIn]`. It is future-compatible and should be equivalent to `[globalVar = TSFE : beUserLogin > 0]` in TYPO3 >=9.4.

**Comment by kevinandrewsde** [comment]
@mabolek All i can say is that when I add
```
[globalVar = TSFE : beUserLogin > 0]
[global]
```
to the top of my root template, everything works, regardless of this commit, and when i add
```
[backend.user.isLoggedIn]
[global]
```
the pages go white in the frontend :)

**Comment by mabolek** [comment]
@kevinandrewsde Do you have `[SYS][features][TypoScript.strictSyntax]` enabled or disabled? (See: https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Conditions/Index.html#upgrading)

**Comment by kevinandrewsde** [comment]
@mabolek We have strict syntax on. But are willing to disable it on all installations if necessary.

**Pull request merged**
