### PR TITLE
[BUGFIX] init NewContentElementController with id and language uid

### PR DESCRIPTION
**Pull request by anjeylink**
@mabolek this should fix issue #376

### CODE REVIEW

**Comment by anjeylink** [comment]
@mabolek I agree that XCLASS is not a good solution. 

Anyway I don't think it's a bug of TYPO3, since "NewContentElementController" was designed to work in BE with "id" parameter and extension is using it on FE where new routing for URLs is used.

**Comment by mabolek** [comment]
@anjeylink Editing should work in the frontend as well as the backend, and loading the wrong PageTS could have implications elsewhere too. Let's anyway wait for the response to the Forge ticket.

**Comment by mabolek** [comment]
@anjeylink Here's a way to solve the issue without an XCLASS:

```
$myRequest = $GLOBALS['TYPO3_REQUEST']->withQueryParams(['id' => $tsfe->id]);
$controller = GeneralUtility::makeInstance(NewContentElementController::class);
$controller->init($myRequest);
$controller->wizardArray();
```

(Thanks to @bmack for the code example.)

**Comment by anjeylink** [comment]
@mabolek I'll open another PR

**Pull request closed without merging**
