### PR TITLE
[BUGFIX] Default to maximized web_view state if BE user never changed it

### PR DESCRIPTION
**Pull request by webian**
If the BE user never changed the web_view state then `$this->getBackendUser()->uc['moduleData']['web_view']['States']['current']` is null and triggers PHP8 warning.

Also the former behaviour was to display the website maximized but also wrongly select the "Custom" preset. Now it select the "Maximized" preset.

### CODE REVIEW

**Review by MattiasNilsson — APPROVED** [review]

**Comment by EcoGabe** [comment]
> This spacer is not needed anymore since the CKeditor toolbar is now placed inside .t3-frontend-editing__toolbars-wrapper

How did you determine the spacer is obsolete? As far as I can tell, with the latest changes, the top bar is burying the inline actions again.

Screenshot 2023-09-22 150511
Screenshot 2023-09-22 150717

It doesn't matter where the toolbars are nested; As long as inline actions aren't in front, the top-most buttons won't be clickable under the huge bar at the top. This was the reason for the spacer: to allow for space to click and drag those buttons.

**Comment by webian** [comment]
Hi @EcoGabe, 
if I understood correctly what you wrote, in the first screenshot the inline action buttons [1] are hidden under the module doc header because you scrolled down the FE page. In the second screenshot, however, they are visible because you scrolled up.

I don't understand where the problem lies. It is normal that when you scroll down, the contents end up under the module doc header, this happens in other TYPO3 modules too (e.g: page/list module).

[1] 
hc3z1crj

**Comment by EcoGabe** [comment]
I didn't scroll anything. In the second screenshot, I manually added the spacer back.

**Comment by EcoGabe** [comment]
There are no scroll bars in either environment. The problem is if there is no **non**-editable space at the top, there is nothing to push the **editable** content into view. Getting rid of the spacer works if you have breadcrumbs, header buttons, banner logos etc. But that shouldn't be an expectation to use frontend editing.

**Comment by EcoGabe** [comment]
image
Just so there isn't any more confusion, here's the full page on the latest branch. No scrollbars; No way to scroll up or down; No possible way to see what's above "Header"; No way to access or click the Move, Edit, Hide, and Delete buttons.

**Comment by webian** [comment]
This should be handled dynamically with Javascript. Like "If the first editable element of the page begins at 0, add a spacer as high as the inline actions btns".

**Comment by EcoGabe** [comment]
It was handled with JavaScript, before its removal in d9a02e83b0e8b7caa8f232f9086b22f586007c5b

```js
$iframe.on('load', function () {  // on load
  let $spacer = $iframe.contents().find('.t3-frontend-editing__spacer'); // find spacer if it exists
  if (!$spacer.length) { // if not
    $spacer = $('<div/>').addClass('t3-frontend-editing__spacer'); // create one
    const $body = $iframe.contents().find('body'); 
    $body.prepend($spacer); // append to body
    $body.find('.t3-frontend-editing__inline-actions').first().each((index, div) => { // check if there is space at the top
      // between the top and the first inline-actions
      if (div.offsetTop < 26) { // if less than 26 pixels of space (the height of inline-actions)
        $spacer.css({height: '26px', width: '100%'}); // add 26 pixels of space
      }
    });
  }
});
```

**Comment by webian** [comment]
OK. I hadn't really considered the purpose of that piece of code when I deleted it. I'll fix it.

**Comment by webian** [comment]
Btw, that code always and in every case inserts the spacer, so I removed it because I didn't understand the purpose of it because I was fixing a lot of things.

That code adds the spacer even if not needed because https://github.com/FriendsOfTYPO3/frontend_editing/blob/63151ab7309a35716225866cd3c8ff649437634f/Resources/Public/JavaScript/FrontendEditing.js#L162 offsetTop returns the top position relative to its parent that is .t3-frontend-editing__ce not the top of the page and also because the display of .t3-frontend-editing__inline-actions is 'none' until mouse hovers its CE so its height is 0 so it is 0 also its offsetTop from its parent.

I'm working on fixing this and reintroduce the spacer only if needed.

**Comment by webian** [comment]
Also, at that point inline_editing.css is not yet loaded so the inline actions toolbar has no style applied and its height is much more than 26 so we can't rely on its position/appearance at that moment.

The code must be placed in .on('load') of inline_editing.css

**Pull request merged**
