### PR TITLE
V9 changes

### PR DESCRIPTION
**Pull request by codegm**

### CODE REVIEW

**Comment by codegm** [comment]
How to handle the failing tests about routes missing? The uri builder function is used before in the extension, in other classes. For the same route.

**Comment by mabolek** [comment]
Hi! @codegm!

Have you had time to look at my review? You should only have to add two lines for this PR to be mergeable. I'd love to be able to include it in a release this week.

**Comment by codegm** [comment]
The Backend routes are initialized in the fe middleware 'BackendUserAuthenticator'. In my eyes, no need to doing it again.

In 'real' the code is working (can say this for v9). Only the test scenario is failing.

**Comment by mabolek** [comment]
Thanks for your efforts, @codegm.

Maybe we have to initialize the routes in the tests. I'll have a look at it.

**Comment by codegm** [comment]
Now its green :), but if this is really the right way to 'initialize' the core for testing, iam not sure

**Pull request merged**
